TOPLEVEL_LANG = verilog
VERILOG_SOURCES = ../pwm.v

TOPLEVEL = pwm           # <-- change this to match your module name
MODULE = test_pwm        # Python file name without `.py`

SIM = verilator
WAVES = 1

include $(shell cocotb-config --makefiles)/Makefile.sim


